'use client'

import { useEffect, useState } from 'react'
import { apiFetch } from '@/lib/api'
import CrudList, { entityConfigs, type EntityKey } from './CrudList'
import PromotionManager from './PromotionManager'
import styles from './admin.module.css'

type Item = { id: number; name: string; code?: string }

export default function ContentScreen() {
  const [entity, setEntity] = useState<EntityKey>('chapters')
  const [courseId, setCourseId] = useState('')
  const [chapterId, setChapterId] = useState('')
  const [courses, setCourses] = useState<Item[]>([])
  const [chapters, setChapters] = useState<Item[]>([])
  const [topics, setTopics] = useState<Item[]>([])
  const [topicId, setTopicId] = useState('')

  useEffect(() => {
    apiFetch<{ items: Item[] }>('/courses?page=1&page_size=100')
      .then((value) => setCourses(value.items))
      .catch(() => setCourses([]))
  }, [])

  useEffect(() => {
    setChapterId('')
    setTopicId('')
    setTopics([])
    if (!courseId) {
      setChapters([])
      return
    }
    apiFetch<{ items: Item[] }>(
      '/chapters?course_id=' + courseId + '&page=1&page_size=100',
    )
      .then((value) => setChapters(value.items))
      .catch(() => setChapters([]))
  }, [courseId])

  useEffect(() => {
    setTopicId('')
    if (!chapterId || entity !== 'topics') { setTopics([]); return }
    apiFetch<{ items: Item[] }>('/topics?chapter_id=' + chapterId + '&page=1&page_size=100').then((value) => setTopics(value.items)).catch(() => setTopics([]))
  }, [chapterId, entity])

  const config = entityConfigs.find((item) => item.key === entity)!

  return (
    <section>
      <header className={styles.header}>
        <span>ACADEMIC CONTENT</span>
        <h1>Chapters & topics</h1>
        <p>Manage learning content beneath the canonical Course Registry. Critical points are entered by admins, not generated by Havan.</p>
      </header>

      <div className={styles.tabs}>
        {entityConfigs.map((item) => (
          <button
            className={entity === item.key ? styles.active : ''}
            key={item.key}
            onClick={() => {
              setEntity(item.key)
              setChapterId('')
              setTopicId('')
            }}
          >
            {item.label}
          </button>
        ))}
      </div>

      <div className={styles.selectors}>
        <label>
          Course
          <select value={courseId} onChange={(event) => setCourseId(event.target.value)}>
            <option value="">Choose a Course Registry course</option>
            {courses.map((item) => (
              <option key={item.id} value={item.id}>
                {item.code || ''} · {item.name}
              </option>
            ))}
          </select>
        </label>

        {(entity === 'topics' || entity === 'chapters') && (
          <label>
            Chapter
            <select
              value={chapterId}
              onChange={(event) => setChapterId(event.target.value)}
              disabled={!courseId}
            >
              <option value="">Choose a chapter</option>
              {chapters.map((item) => (
                <option key={item.id} value={item.id}>
                  {item.name}
                </option>
              ))}
            </select>
          </label>
        )}
        {entity === 'topics' && chapterId && (
          <label>Topic
            <select value={topicId} onChange={(event) => setTopicId(event.target.value)}>
              <option value="">Choose a topic</option>
              {topics.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}
            </select>
          </label>
        )}
      </div>

      {!courseId ? (
        <div className={styles.empty}>Choose a canonical course first. Content cannot exist without a course.</div>
      ) : entity === 'topics' && !chapterId ? (
        <div className={styles.empty}>Choose a chapter before editing its topics.</div>
      ) : (
        <>
          <CrudList config={config} parentId={entity === 'chapters' ? courseId : chapterId} />
          {entity === 'chapters' && chapterId && <PromotionManager parentType="chapter" parentId={chapterId} />}
          {entity === 'topics' && topicId && <PromotionManager parentType="topic" parentId={topicId} />}
        </>
      )}
    </section>
  )
}
