'use client'
import {useEffect,useState} from 'react'
import {apiFetch} from '@/lib/api'
import styles from './admin.module.css'
export type EntityKey='courses'|'chapters'|'topics'
type Field={key:string;label:string;type?:'text'|'number'|'textarea'}
type Config={key:EntityKey;label:string;endpoint:string;parentKey?:string;fields:Field[];create?:boolean}
export const entityConfigs:Config[]=[{key:'courses',label:'Courses',endpoint:'/courses',create:false,fields:[{key:'code',label:'Code'},{key:'name',label:'Name'},{key:'credit_hours',label:'Credits',type:'number'}]},{key:'chapters',label:'Chapters',endpoint:'/chapters',parentKey:'course_id',fields:[{key:'name',label:'Name'},{key:'order_index',label:'Order',type:'number'},{key:'important_points',label:'Important points',type:'textarea'}]},{key:'topics',label:'Topics',endpoint:'/topics',parentKey:'chapter_id',fields:[{key:'name',label:'Name'},{key:'order_index',label:'Order',type:'number'},{key:'estimated_study_minutes',label:'Study minutes',type:'number'},{key:'difficulty',label:'Difficulty 1–5',type:'number'},{key:'exam_importance',label:'Exam importance 0–1',type:'number'},{key:'important_points',label:'Important points',type:'textarea'}]}]
export default function CrudList({config,parentId}:{config:Config;parentId?:string}){const [items,setItems]=useState<Record<string,unknown>[]>([]),[edit,setEdit]=useState<Record<string,unknown>|null|undefined>(undefined),[form,setForm]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=()=>{const q=parentId&&config.parentKey?'?'+config.parentKey+'='+parentId+'&page=1&page_size=100':'?page=1&page_size=100';apiFetch<{items:Record<string,unknown>[]}>(config.endpoint+q).then(x=>setItems(x.items)).catch(e=>setError(e instanceof Error?e.message:'Could not load content.'))};useEffect(load,[parentId,config.endpoint])
 function start(x:Record<string,unknown>|null){setEdit(x);setForm(Object.fromEntries(config.fields.map(f=>[f.key,String(x?.[f.key]??'')])))}
 async function save(){setBusy(true);try{const body:Record<string,unknown>={...form};for(const f of config.fields)if(f.type==='number'&&body[f.key]!=='')body[f.key]=Number(body[f.key]);const x=await apiFetch<Record<string,unknown>>(edit?config.endpoint+'/'+String(edit.id):config.endpoint,{method:edit?'PATCH':'POST',body:JSON.stringify({...body,...(parentId&&config.parentKey?{[config.parentKey]:Number(parentId)}:{})})});setItems(v=>edit?v.map(i=>i.id===x.id?x:i):[x,...v]);setEdit(undefined)}catch(e){setError(e instanceof Error?e.message:'Could not save content.')}finally{setBusy(false)}}
 async function archive(x:Record<string,unknown>){if(!confirm('Deactivate this record? It remains in the catalog.'))return;try{await apiFetch(config.endpoint+'/'+x.id,{method:'PATCH',body:JSON.stringify({status:'INACTIVE'})});load()}catch(e){setError(e instanceof Error?e.message:'Could not update record.')}}
 return <div className={styles.crud}><div className={styles.crudHead}><div><h2>{config.label}</h2><p>Edit reusable academic content. Deactivation does not delete content.</p></div>{config.create!==false&&<button onClick={()=>start(null)}>New</button>}</div>{error&&<div className={styles.alert}>{error}</div>}<div className={styles.crudGrid}><div className={styles.list}>{items.map(x=><article className={styles.row} key={String(x.id)}><div><b>{String(x.code||'Record')}</b><span>{String(x.name||'')}</span><small>{String(x.status||'')}</small></div><button onClick={()=>start(x)}>Edit</button><button className={styles.danger} onClick={()=>archive(x)}>Deactivate</button></article>)}{!items.length&&<p className={styles.empty}>No records in this scope.</p>}</div>{edit!==undefined&&<div className={styles.editor}><h3>{edit?'Edit record':'New record'}</h3>{config.fields.map(f=><label key={f.key}>{f.label}{f.type==='textarea'?<textarea value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input type={f.type||'text'} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<div className={styles.actions}><button onClick={()=>setEdit(undefined)}>Cancel</button><button className={styles.primary} disabled={busy} onClick={save}>{busy?'Saving…':'Save'}</button></div></div>}</div></div>}
