'use client'
import {useEffect,useMemo,useState} from 'react'
import {apiFetch} from '@/lib/api'
import styles from './admin.module.css'
type U={id:number;name:string;code:string};type C={id:number;university_id:number;name:string;version:string;status:string};type S={id:number;curriculum_id:number;name:string;code:string;status:string};type Course={id:number;code:string;name:string;credit_hours:number|null;academic_scope:string;status:string};type M={id:number;stream_id:number;course_id:number;course_code:string;course_name:string;credit_hours:number|null;semester_number:number;order_index:number}
export default function MappingScreen(){
 const [u,setU]=useState<U[]>([]),[c,setC]=useState<C[]>([]),[s,setS]=useState<S[]>([]),[courses,setCourses]=useState<Course[]>([]),[maps,setMaps]=useState<M[]>([]);const [uid,setUid]=useState(''),[cid,setCid]=useState(''),[sid,setSid]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState('')
 useEffect(()=>{Promise.all([apiFetch<{items:U[]}>('/universities?page=1&page_size=100'),apiFetch<{items:C[]}>('/curriculums?page=1&page_size=100'),apiFetch<{items:S[]}>('/streams?page=1&page_size=100'),apiFetch<Course[]>('/university-course-mappings/courses?status_filter=ACTIVE')]).then(([a,b,d,e])=>{setU(a.items);setC(b.items);setS(d.items);setCourses(e);if(a.items[0])setUid(String(a.items[0].id))}).catch(e=>setError(e instanceof Error?e.message:'Could not load mapping data.'))},[])
 const cs=useMemo(()=>c.filter(x=>String(x.university_id)===uid),[c,uid]),ss=useMemo(()=>s.filter(x=>String(x.curriculum_id)===cid&&x.status==='ACTIVE'),[s,cid]);const mapped=new Set(maps.map(x=>x.course_id));const filtered=courses.filter(x=>{const q=search.toLowerCase().trim();return !q||x.code.toLowerCase().includes(q)||x.name.toLowerCase().includes(q)})
 useEffect(()=>{const x=cs.find(v=>v.status==='ACTIVE')||cs[0];setCid(x?String(x.id):'')},[cs]);useEffect(()=>{const x=ss[0];setSid(x?String(x.id):'')},[ss]);useEffect(()=>{if(sid)apiFetch<M[]>('/university-course-mappings?stream_id='+sid).then(setMaps).catch(e=>setError(e instanceof Error?e.message:'Could not load mapped courses.'));else setMaps([])},[sid])
 async function add(course:Course,semester:number){setBusy(course.id);try{const order=Math.max(0,...maps.filter(x=>x.semester_number===semester).map(x=>x.order_index))+1;const x=await apiFetch<M>('/university-course-mappings',{method:'POST',body:JSON.stringify({stream_id:+sid,course_id:course.id,semester_number:semester,order_index:order,status:'ACTIVE'})});setMaps(v=>[...v,x])}catch(e){setError(e instanceof Error?e.message:'Could not add course.')}finally{setBusy(null)}}
 async function move(x:M){setBusy(x.course_id);try{const semester=x.semester_number===1?2:1;const order=Math.max(0,...maps.filter(v=>v.semester_number===semester).map(v=>v.order_index))+1;const y=await apiFetch<M>('/university-course-mappings/'+x.id,{method:'PATCH',body:JSON.stringify({semester_number:semester,order_index:order})});setMaps(v=>v.map(a=>a.id===y.id?y:a))}catch(e){setError(e instanceof Error?e.message:'Could not move course.')}finally{setBusy(null)}}
 async function remove(x:M){if(!confirm('Remove this course from this stream? The course content will not be deleted.'))return;setBusy(x.course_id);try{await apiFetch('/university-course-mappings/'+x.id,{method:'DELETE'});setMaps(v=>v.filter(a=>a.id!==x.id))}catch(e){setError(e instanceof Error?e.message:'Could not remove course.')}finally{setBusy(null)}}
 const card=(x:M)=><div className={styles.row} key={x.id}><div><b>{x.course_code}</b><span>{x.course_name}</span></div><button disabled={busy===x.course_id} onClick={()=>move(x)}>Move to {x.semester_number===1?'2':'1'}</button><button className={styles.danger} disabled={busy===x.course_id} onClick={()=>remove(x)}>Remove</button></div>
 const one=maps.filter(x=>x.semester_number===1),two=maps.filter(x=>x.semester_number===2)
 return <section><header className={styles.header}><span>SETUP</span><h1>Universities & mapping</h1><p>Choose a stream, then place each course in Semester 1 or 2. Course content stays reusable.</p></header>{error&&<div className={styles.alert}>{error}</div>}<div className={styles.selectors}><label>University<select value={uid} onChange={e=>setUid(e.target.value)}>{u.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Curriculum<select value={cid} onChange={e=>setCid(e.target.value)}>{cs.map(x=><option key={x.id} value={x.id}>{x.name} · v{x.version}</option>)}</select></label><label>Stream<select value={sid} onChange={e=>setSid(e.target.value)}>{ss.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label></div><div className={styles.catalog}><div><h2>Add a course</h2><p>Search the catalog and place an unmapped course.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search course code or name…"/>{filtered.filter(x=>!mapped.has(x.id)).slice(0,20).map(x=><div className={styles.row} key={x.id}><div><b>{x.code}</b><span>{x.name}</span></div><button disabled={!sid||busy===x.id} onClick={()=>add(x,1)}>+ Semester 1</button><button disabled={!sid||busy===x.id} onClick={()=>add(x,2)}>+ Semester 2</button></div>)}</div><div className={styles.semesters}><div className={styles.panel}><h2>Semester 1 <small>{one.length} courses</small></h2>{one.map(card)}{!one.length&&<p className={styles.empty}>No courses mapped yet.</p>}</div><div className={styles.panel}><h2>Semester 2 <small>{two.length} courses</small></h2>{two.map(card)}{!two.length&&<p className={styles.empty}>No courses mapped yet.</p>}</div></div></section>
}
